# Generated by Django 2.0.5 on 2019-08-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_servicetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetemplate',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
