# Generated by Django 2.0.5 on 2019-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_auto_20190821_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_count', models.IntegerField()),
                ('date', models.DateField()),
                ('template', models.ForeignKey(on_delete='CASCADE', to='church.ServiceTemplate')),
            ],
        ),
    ]
